server:
  port: 8081

spring:
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:coinDesk
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl: none
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  main:
    allow-circular-references: true