CREATE TABLE CURRENCY (
  CODE VARCHAR(15) NOT NULL,
  CURRENCY_NAME VARCHAR(15) NOT NULL DEFAULT '',
  PRIMARY KEY(CODE)
);
INSERT INTO CURRENCY VALUES('GBP', '英鎊');
INSERT INTO CURRENCY VALUES('EUR', '歐元');